### ISSUE TITLE
Learn advanced react and provide feedback on the workshop

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/advanced-react-patterns-v2#6]
Hey folks! I'd love it if some of you could help me out with this workshop and make sure it's good to go! Please just follow the README instructions and let me know where you get stuck and what could be improved. Each of the exercises should be commented well enough for you to get everything done on your own without instruction.

Let me know if there are typos, legit errors, or anything that's unclear.

One thing I know is that the snapshots are failing on codesandbox. Hopefully I can get those working, but it should be working locally :) Thanks!

**Comment by FWeinb** [comment]
First of all this is extremely valuable! Thanks for all the effort. I worked throw it on codesandbox (Great platform for these courses). 

Some of my findings:
#### 02.js
```js
// The button will be responsible for rendering the <Switch /> (with the right pros)
```
Not quite sure but I think this should be `(with the right *props*)`

#### 03.js
```js
// 💰: You'll need to move this below the `toggle` function. See
// if you can figure out why :)
```
Figured it out but would be nice to have a little explanation in the final version. 

#### 06.js
Even for the final version I get this error when clicking on the "on"/"off" button under the switch:
 >proxyConsole.js:72 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

##### I will add more findings tonight need to head out now... 
----

In general I find it very rewarding to work through these tiny problem sets. I can clearly see each piece of information fit right into each other. The amount of "work" in each step is perfectly measured and doesn't lead to any frustration. 
Just one thing I don't really get. There are are some places where you are using 🐨 as a marker for "work" and other times there is `TODO` maybe there is a distinction between these places but I would greatly appreciate a short intro and what each emojis stands. 

It really shows that this is v2, astonishing how incredible the pacing of this is. Thanks for creating such great content! 

Looking forward of doing the rest of it tonight.

**Comment by kentcdodds** [comment]
Thank you so much @FWeinb! This is very valuable feedback!

> 02.js

You're right, that's a typo. PR anyone?

> 03.js

Yeah, perhaps I should explain it in some comments :+1:

> 06.js

That appears to be a bug. I'll need to look into it (or anyone else is welcome to address it in a PR if you so desire).

> 🐨 vs `TODO`

Anything that's `TODO` in the exercises should be 🐨. If it's not then I missed it :sweat_smile: PR for that too would be cool :+1:

**Comment by FWeinb** [comment]
Glad you find this feedback valuable. I added my remaining thoughts on the other exercises. I could make a PR to fix these issues if you would like.

**Comment by kentcdodds** [comment]
Thanks a ton!

> 07.js

Yes, the naming is unfortunate. I totally understand what you're saying. I'll improve that.

> 09.js

Great point. I'll make that more clear :+1:

> 10.js

Good points. I'll make that more clear too.

> 10-primer.js

That was a mistake. 10-primer.js is _supposed_ to come before 10.js. Sorry 😅

Thanks again!

**Comment by AWolf81** [comment]
## 01 to 09.js
These excersises are good to do with your comments in the code.
  
## 10-primer.js & 10.js
In the list of the excersises it would be good to have primer before the final example. So the order in the list should be changed:
- 10-primer.js
- 10.js

**Screenshot of the current list:**
![grafik](https://user-images.githubusercontent.com/3046542/38772638-20827e28-403c-11e8-82e8-b3930047c303.png)

I have exidentially clicked on 10.js in the preview and was wondering why my code wasn't working. It was because I worked at the primer example and it took me a while to detect that I was running the wrong excersise in the preview.

Changing order just needs one change in app.js files array.

**10.js**
For me it is still difficult to follow how the `internalSetState` method is working. I haven't used the mapping like you're doing it before. Maybe I have to read a bit more about it in the docs.

## 13.js
There is a "typo" in `MyInput` Component. Line 78 in excersise file not matching the code from the final file. So the input field is not updating properly. I can edit it and send a PR for this.

Also the commented import statement for Redux would be good at this example and also a brief description what the component should do would be great.

I like the idea of using Redux like in this example but I'm not sure if this is best practice. I think it's better to use one Redux store and use the Redux provider and connect the component to that store.
If that's right, you could add that as a comment there.

## My thoughts to the workshop
You did a great job here. It was fun to work my way through it. Thanks for your work.
But I noticed that I'm still a React beginner at some parts - so especially at 10.js I had to peek at the solution to get the excersise done.

A possible improvement: 
It would be good to have failing unit tests at each file because of these missing lines of the excersises. E.g. for 01.js a test like - `it should toggle on state` and `it should call onToggle prop`. So it would be easier to see if every part is properly implemented.

**Comment by kentcdodds** [comment]
Thank you so much for the help @AWolf81!

> 10.js

I think that I'll refactor from using the `map` calls to just creating new variable declarations instead. It's a little more verbose, but I think that it'll be a little less confusing for people. Thanks for that feedback.

> 13.js

Rendux isn't really intended to be a best practice or anything. People can implement it however they like. So I'm not entirely concerned about that bit so long as it works :)

> A possible improvement:

Did you notice that there actually _are_ unit tests for each exercise? As noted in the README you're supposed to swap the import of the final version with the import of the exercise and make the test pass. Was there something that I could have clarified there?

**Comment by dlannoye** [comment]
On exercise 8 I have a solution that passes the tests, but doesn't correctly call the state reducer with the correct arguments. My internalSetState code looks like this:
```
  internalSetState = (updates, callback) => {
    this.setState(this.props.stateReducer ? this.props.stateReducer(this.state, updates) : updates, callback);
  }
```
Which doesn't properly 'compute' the updates if a function is used before passing them to the stateReducer like you do in the final solution. If this isn't intended let me know and I can try to update the tests to handle this case.

**Comment by kentcdodds** [comment]
Thanks @colinrcummings. As [I noted](https://github.com/kentcdodds/advanced-react-patterns-v2/pull/17#discussion_r182189975) in a PR that attempted to remove it:

> This is still useful in some situations, so I definitely suggest continuing to expose this. Remember that prop getters are just helpers and should generally not be the only way to accomplish certain tasks :) Thanks anyway!

:)

**Comment by colinrcummings** [comment]
@kentcdodds, how do you feel about the following to fix the `displayName` in exercises with HOCs?

[`withToggle`](https://github.com/kentcdodds/advanced-react-patterns-v2/blob/master/src/exercises-final/12.js#L113) (exercise 12):

*code:*

```
function withToggle(Component) {
  class Wrapper extends React.Component {
    render() {
      const { forwardedRef, ...rest } = this.props;

      return (
        <Toggle.Consumer>
          {toggle => <Component {...rest} toggle={toggle} ref={forwardedRef} />}
        </Toggle.Consumer>
      );
    }
  }

  Wrapper.displayName = `withToggle(${Component.displayName ||
    Component.name})`;

  const forwardRef = React.forwardRef((props, ref) => (
    <Wrapper {...props} forwardedRef={ref} />
  ));

  return hoistNonReactStatics(forwardRef, Component);
}
```

*react devtools:*

![image](https://user-images.githubusercontent.com/9815009/38903697-203506f4-4274-11e8-9d10-63ee86d0203a.png)

[`withRendux`](https://github.com/kentcdodds/advanced-react-patterns-v2/blob/master/src/exercises-final/13.js#L54) (exercise 13):

*code:*

```
function withRendux(Component) {
  class Wrapper extends React.Component {
    render() {
      const { forwardedRef, ...rest } = this.props;

      return (
        <Rendux.Consumer>
          {rendux => <Component {...rest} rendux={rendux} ref={forwardedRef} />}
        </Rendux.Consumer>
      );
    }
  }

  Wrapper.displayName = `withRendux(${Component.displayName ||
    Component.name ||
    'Wrapper'})`;

  const forwardRef = React.forwardRef((props, ref) => (
    <Wrapper {...props} forwardedRef={ref} />
  ));

  return hoistNonReactStatics(forwardRef, Component);
}
```
*react devtools:*

![image](https://user-images.githubusercontent.com/9815009/38903718-4af884d8-4274-11e8-8732-8dc7194ffeef.png)

In exercise 13, I believe the  `displayName` for [`StatePrinter`](https://github.com/kentcdodds/advanced-react-patterns-v2/blob/master/src/exercises-final/13.js#L120) isn't being passed through because it's a SFC in the same file ([reference](https://github.com/facebook/react-devtools/issues/267)). In exercise 12, on the other hand, the  `displayName` for [`Subtitle`](https://github.com/kentcdodds/advanced-react-patterns-v2/blob/master/src/exercises-final/12.js#L130) is being passed through fine because it's a true `Component`.

**Comment by kentcdodds** [comment]
Ah yes, that makes sense. So a solution would be to change StatePrinter to:

```js
const StatePrinter = withRendux(function StatePrinter({rendux}) {
  return (
    <div style={{textAlign: 'left'}}>
      state:
      <pre data-testid="printed-state">
        {JSON.stringify(rendux.state, null, 2)}
      </pre>
    </div>
  )
})
```

Anyone want to do that?

**Comment by colinrcummings** [comment]
Sure thing. I'll work on a PR this weekend.
